In [1]:
import pandas as pd
df=pd.read_csv('cardata.csv')
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [2]:
# selecting indepentand and target
input=df.drop('Selling_Price',axis='columns')
target=df['Selling_Price']
input.head()

,Car_Name,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,6.87,42450,Diesel,Dealer,Manual,0

In [19]:
target.head()

0    3.35
1    4.75
2    7.25
3    2.85
4    4.60
Name: Selling_Price, dtype: float64

In [20]:
# from sklearn.preprocessing import LabelEncoder
# le=LabelEncoder()
# for cols in input:
#     df[cols]=le.fit_transform(df[cols])
# input=df

# input.tail()

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(input,target,test_size=0.3,random_state=100)
print('x_train',X_train.head())
print('x_test',X_test.head())
print('y_train',y_train.head())
print('y_test',y_test.head())

x_train      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  \
156        54    14             16              4          49          2
98         71    10            110            133         139          2
276        69    12            123            123          82          2
203        83     8             54             52         158          2
123        46    10             29             32         143          2

     Seller_Type  Transmission  Owner
156            1             1      0
98             0             1      0
276            0             1      0
203            0             1      0
123            1             1      0
x_test      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  \
199        33     4              1              8         157          2
201        84     7             58             70         169          1
111        48    13             33             33          30          2
125        47     6             27             35         121          2
46         90    10             49             53         179          2

     Seller_Type  Transmission  Owner
199            1             1      0
201            0             1      1
111            1             1      0
125            1             1      0
46             0             1      0
y_train 156    0.48
98     7.05
276    8.65
203    2.95
123    1.00
Name: Selling_Price, dtype: float64
y_test 199    0.12
201    3.25
111    1.15
125    0.90
46     2.65
Name: Selling_Price, dtype: float64

In [22]:
from sklearn import tree
model=tree.DecisionTreeClassifier()
model.fit(input,target)

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.